version: '2'

services:
    traefik:
        image: traefik:v2.2
        command: --providers.docker
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    plantuml:
        image: registry.kher.nl/tlc/plantuml-server:URLWorking
        restart: always
        environment:
            PLANTUML_JAVASCRIPT_UNSECURE: 'true'
            BASE_URL: plantuml
        labels:
            - "traefik.http.routers.uml.rule=PathPrefix(`/plantuml`)"

    nginx:
        image: 'nginx'
        restart: always
        volumes:
            - ./src:/usr/share/nginx/html:ro
        labels:
            - "traefik.http.routers.nginx.rule=PathPrefix(`/`)"
        
        
    spot:
        image: gitlab-registry.lre.epita.fr/spot/spot-web
        restart: always
        labels:
            - "traefik.http.routers.spot.rule=PathPrefix(`/api`)"

